spring:
  application:
    name: accounts

  datasource:
    url: jdbc:h2:mem:accounts
    driver-class-name: org.h2.Driver
    username: sc
    password: sc
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  #        type:
  #          preferred_enum_jdbc_type: VARCHAR


  cloud:
    openfeign:
      client:
        config:
          clients:
            connectTimeout: 2000
            readTimeout: 5000

resilience4j:
  retry:
    instances:
      clientServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.RetryableException
          - feign.FeignException.InternalServerError
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - java.io.IOException
        ignore-exceptions:
          - feign.FeignException.BadRequest
          - feign.FeignException.NotFound

clients-service:
  ribbon:
    listOfServers: localhost:8082

server:
  port: 8081
