services:
  clients-ms:
    image: juandavyc/clients:s1
    container_name: clients-ms
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    networks:
      - devsu-network

  accounts-ms:
    image: juandavyc/accounts:s1
    container_name: accounts-ms
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - CLIENTS_SERVICE_URL=http://clients-ms:8082
    depends_on:
      - clients-ms
    networks:
      - devsu-network

networks:
  devsu-network:
    driver: bridge